import { useState, useRef } from "react";
const CATEGORIAS = {
  "🥩 Carnes": { color: "#c0392b", glow: "rgba(192,57,43,0.35)", items: [{ nombre: "Asado de tira", unidad: "kg", stock: 12, minimo: 8 },{ nombre: "Vacío", unidad: "kg", stock: 6, minimo: 8 },{ nombre: "Entraña", unidad: "kg", stock: 4, minimo: 5 },{ nombre: "Bife de chorizo", unidad: "kg", stock: 9, minimo: 6 },{ nombre: "Matambre", unidad: "kg", stock: 3, minimo: 4 },{ nombre: "Costillas", unidad: "kg", stock: 10, minimo: 6 },{ nombre: "Pollo entero", unidad: "unidades", stock: 8, minimo: 6 },{ nombre: "Pechuga", unidad: "kg", stock: 5, minimo: 4 }], proveedor: "La Pampa Carnes" },
  "🌭 Embutidos": { color: "#e67e22", glow: "rgba(230,126,34,0.35)", items: [{ nombre: "Chorizo", unidad: "kg", stock: 7, minimo: 5 },{ nombre: "Morcilla", unidad: "kg", stock: 2, minimo: 4 },{ nombre: "Salchicha parrillera", unidad: "kg", stock: 5, minimo: 3 },{ nombre: "Provoleta", unidad: "kg", stock: 3, minimo: 3 }], proveedor: "La Pampa Carnes" },
  "🥬 Verduras": { color: "#27ae60", glow: "rgba(39,174,96,0.35)", items: [{ nombre: "Lechuga", unidad: "unidades", stock: 5, minimo: 4 },{ nombre: "Tomate", unidad: "kg", stock: 3, minimo: 5 },{ nombre: "Cebolla", unidad: "kg", stock: 8, minimo: 5 },{ nombre: "Papas", unidad: "kg", stock: 15, minimo: 10 },{ nombre: "Limón", unidad: "unidades", stock: 20, minimo: 15 },{ nombre: "Pimiento", unidad: "kg", stock: 2, minimo: 3 }], proveedor: "Verdulería Don José" },
  "🧂 Despensa": { color: "#f39c12", glow: "rgba(243,156,18,0.35)", items: [{ nombre: "Sal gruesa", unidad: "kg", stock: 4, minimo: 3 },{ nombre: "Chimichurri", unidad: "kg", stock: 1, minimo: 2 },{ nombre: "Aceite", unidad: "litros", stock: 5, minimo: 4 },{ nombre: "Pan de campo", unidad: "unidades", stock: 30, minimo: 20 },{ nombre: "Carbón", unidad: "kg", stock: 20, minimo: 15 },{ nombre: "Leña", unidad: "kg", stock: 35, minimo: 20 }], proveedor: "Almacén Central" },
  "🍺 Bebidas": { color: "#2980b9", glow: "rgba(41,128,185,0.35)", items: [{ nombre: "Cerveza rubia", unidad: "unidades", stock: 48, minimo: 36 },{ nombre: "Vino tinto", unidad: "botellas", stock: 12, minimo: 10 },{ nombre: "Gaseosa", unidad: "unidades", stock: 24, minimo: 18 },{ nombre: "Agua mineral", unidad: "unidades", stock: 20, minimo: 12 },{ nombre: "Fernet", unidad: "botellas", stock: 4, minimo: 3 }], proveedor: "Distribuidora El Barril" },
};
const buildStock = () => Object.entries(CATEGORIAS).flatMap(([cat, data]) => data.items.map((item) => ({ id: cat+"-"+item.nombre, nombre: item.nombre, categoria: cat, proveedor: data.proveedor, unidad: item.unidad, stock: item.stock, minimo: item.minimo, actualizado: "hoy" })));
export default function App() { return <div style={{padding:40,color:"white",background:"#111",minHeight:"100vh"}}><h1>🔥 ParrillaStock</h1><p>App cargando correctamente.</p></div>; }
